package ai.ravenroot.extensions.kafka;

import ai.ravenroot.api.security.SecretValue;
import ai.ravenroot.api.security.egress.ReservedNetworkPolicy;
import org.junit.jupiter.api.Test;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Optional;
import java.util.Set;
import java.util.concurrent.atomic.AtomicInteger;
import static org.junit.jupiter.api.Assertions.*;

class KafkaProduceContractTest {
    @Test void reservedLiteralProfileIsRefusedBeforeCredentialOrClientAndExactExceptionReachesClient(){
        KafkaProfile base=KafkaTestSupport.profile();
        KafkaProfile literal=new KafkaProfile(base.tenant(),base.name(),java.util.List.of("127.1:9093"),base.clientDnsLookup(),base.tls(),base.saslMechanism(),base.username(),base.credentialRef(),base.clientId(),base.defaultTopic(),base.topics(),base.headers(),base.allowPartition(),base.maxPartition(),base.allowTimestamp(),base.compression(),base.acks(),base.idempotence(),base.retries(),base.maxInFlight(),base.allowAutoCreate(),base.maxConcurrency(),base.maxPerSecond(),base.timeoutMs(),base.maxRecordBytes(),base.bufferMemoryBytes());
        AtomicInteger credentials=new AtomicInteger();var deniedProtocol=new KafkaTestSupport.FakeProtocol(KafkaTestSupport.Event.ACK);
        var denied=new KafkaProduceNodeBehavior(ref->{credentials.incrementAndGet();return Optional.of(new SecretValue("secret".toCharArray()));},(tenant,name)->Optional.of(literal),deniedProtocol,new KafkaRuntimeControls(System::nanoTime,Runnable::run,8,8,32),System::nanoTime,ReservedNetworkPolicy.denyAllReserved());
        assertEquals("PERMANENT_FAILURE",KafkaTestSupport.output(denied.create(KafkaTestSupport.configuration()),KafkaTestSupport.payload()).get("status"));assertEquals(0,credentials.get());assertEquals(0,deniedProtocol.creates.get());
        var allowedProtocol=new KafkaTestSupport.FakeProtocol(KafkaTestSupport.Event.ACK);
        var allowed=new KafkaProduceNodeBehavior(ref->Optional.of(new SecretValue("secret".toCharArray())),(tenant,name)->Optional.of(literal),allowedProtocol,new KafkaRuntimeControls(System::nanoTime,Runnable::run,8,8,32),System::nanoTime,ReservedNetworkPolicy.fromCommaSeparatedExceptions("127.1:LOOPBACK"));
        assertEquals("ACKNOWLEDGED",KafkaTestSupport.output(allowed.create(KafkaTestSupport.configuration()),KafkaTestSupport.payload()).get("status"));assertEquals(1,allowedProtocol.creates.get());
    }
    @Test void acknowledgesOnceWithSanitizedMetadataAndNeverResubmits(){var p=new KafkaTestSupport.FakeProtocol(KafkaTestSupport.Event.ACK);var out=KafkaTestSupport.output(KafkaTestSupport.behavior(p).create(KafkaTestSupport.configuration()),KafkaTestSupport.payload());assertEquals("ACKNOWLEDGED",out.get("status"));assertEquals(1,out.get("attemptCount"));assertEquals(42L,out.get("offset"));assertEquals(1,p.sends.get());assertEquals(1,p.flushes.get());assertEquals(1,p.closes.get());assertFalse(out.toString().contains(KafkaTestSupport.SECRET));}
    @Test void supportsBoundedKeyJsonValueBase64HeadersPartitionAndTimestamp(){var p=new KafkaTestSupport.FakeProtocol(KafkaTestSupport.Event.ACK);var payload=new LinkedHashMap<String,Object>();payload.put("version","kafka.produce.v1");payload.put("keyJson",Map.of("a",1));payload.put("valueBase64","AAEC");payload.put("partition",3);payload.put("timestamp",5L);payload.put("headers",Map.of("trace","abc"));assertEquals("ACKNOWLEDGED",KafkaTestSupport.output(KafkaTestSupport.behavior(p).create(KafkaTestSupport.configuration()),payload).get("status"));var r=p.records.getFirst();assertEquals(3,r.partition());assertEquals(5L,r.timestamp());assertArrayEquals(new byte[]{0,1,2},r.value());assertEquals("abc",new String(r.headers().get("trace"),java.nio.charset.StandardCharsets.UTF_8));}
    @Test void rejectsUnknownAuthorityAndOversizeBeforeCredentialOrClient(){AtomicInteger credentials=new AtomicInteger();var p=new KafkaTestSupport.FakeProtocol();var b=new KafkaProduceNodeBehavior(ref->{credentials.incrementAndGet();return Optional.of(new SecretValue("x".toCharArray()));},(t,n)->Optional.of(KafkaTestSupport.profile()),p,new KafkaRuntimeControls(System::nanoTime,Runnable::run,8,8,32),System::nanoTime);var payload=new LinkedHashMap<>(KafkaTestSupport.payload());payload.put("topic","forbidden");assertEquals("REJECTED",KafkaTestSupport.output(b.create(KafkaTestSupport.configuration()),payload).get("status"));assertEquals(0,credentials.get());assertEquals(0,p.creates.get());payload=new LinkedHashMap<>(KafkaTestSupport.payload());payload.put("headers",Map.of("forbidden","x"));assertEquals("REJECTED",KafkaTestSupport.output(b.create(KafkaTestSupport.configuration()),payload).get("status"));assertEquals(0,credentials.get());}
    @Test void authenticationIsTerminalAndSilentCallbackIsAmbiguous(){var auth=new KafkaTestSupport.FakeProtocol(KafkaTestSupport.Event.AUTH);assertEquals("PERMANENT_FAILURE",KafkaTestSupport.output(KafkaTestSupport.behavior(auth).create(KafkaTestSupport.configuration()),KafkaTestSupport.payload()).get("status"));var silent=new KafkaTestSupport.FakeProtocol(KafkaTestSupport.Event.SILENT);assertEquals("AMBIGUOUS",KafkaTestSupport.output(KafkaTestSupport.behavior(silent).create(KafkaTestSupport.configuration(Map.of("timeoutMs","100"))),KafkaTestSupport.payload()).get("status"));assertEquals(1,silent.sends.get());}
    @Test void mutableProtocolPasswordIsClearedOnEveryExit(){var p=new KafkaTestSupport.FakeProtocol(KafkaTestSupport.Event.ACK);KafkaTestSupport.output(KafkaTestSupport.behavior(p).create(KafkaTestSupport.configuration()),KafkaTestSupport.payload());assertTrue(new String(p.passwords.getFirst()).chars().allMatch(c->c==0));}
    @Test void idempotenceMatrixAndProductionTlsFailClosed(){KafkaProfile valid=KafkaTestSupport.profile();assertThrows(IllegalArgumentException.class,()->copy(valid,"1",true,1,5,true));assertThrows(IllegalArgumentException.class,()->copy(valid,"all",false,1,5,true));assertThrows(IllegalArgumentException.class,()->copy(valid,"all",true,0,5,true));assertThrows(IllegalArgumentException.class,()->copy(valid,"all",true,1,6,true));assertThrows(IllegalArgumentException.class,()->copy(valid,"all",true,1,5,false));assertDoesNotThrow(()->new KafkaProfile(valid.tenant(),valid.name(),java.util.List.of("localhost:9092"),valid.clientDnsLookup(),false,valid.saslMechanism(),valid.username(),valid.credentialRef(),valid.clientId(),valid.defaultTopic(),valid.topics(),valid.headers(),valid.allowPartition(),valid.maxPartition(),valid.allowTimestamp(),valid.compression(),valid.acks(),valid.idempotence(),valid.retries(),valid.maxInFlight(),valid.allowAutoCreate(),valid.maxConcurrency(),valid.maxPerSecond(),valid.timeoutMs(),valid.maxRecordBytes(),valid.bufferMemoryBytes()));}
    @Test void invalidBootstrapPortFailsClosed(){KafkaProfile p=KafkaTestSupport.profile();assertThrows(IllegalArgumentException.class,()->new KafkaProfile(p.tenant(),p.name(),java.util.List.of("broker.example.test:99999"),p.clientDnsLookup(),true,p.saslMechanism(),p.username(),p.credentialRef(),p.clientId(),p.defaultTopic(),p.topics(),p.headers(),p.allowPartition(),p.maxPartition(),p.allowTimestamp(),p.compression(),p.acks(),p.idempotence(),p.retries(),p.maxInFlight(),p.allowAutoCreate(),p.maxConcurrency(),p.maxPerSecond(),p.timeoutMs(),p.maxRecordBytes(),p.bufferMemoryBytes()));}
    @Test void correlationAndTextUtf8FailClosedBeforeSecretsOrClient(){for(String bad:new String[]{" ","a\n","a\t","a\u0085","\uD800","\uDC00"}){var p=new KafkaTestSupport.FakeProtocol();AtomicInteger credentials=new AtomicInteger();var b=new KafkaProduceNodeBehavior(ref->{credentials.incrementAndGet();return Optional.of(new SecretValue("x".toCharArray()));},(t,n)->Optional.of(KafkaTestSupport.profile()),p,new KafkaRuntimeControls(System::nanoTime,Runnable::run,8,8,32),System::nanoTime);assertEquals("REJECTED",KafkaTestSupport.output(b.create(KafkaTestSupport.configuration(Map.of("correlationId",bad))),KafkaTestSupport.payload()).get("status"));var payload=new LinkedHashMap<>(KafkaTestSupport.payload());payload.put("correlationId",bad);assertEquals("REJECTED",KafkaTestSupport.output(b.create(KafkaTestSupport.configuration()),payload).get("status"));payload=new LinkedHashMap<>(KafkaTestSupport.payload());payload.put("valueText","\uD800");assertEquals("REJECTED",KafkaTestSupport.output(b.create(KafkaTestSupport.configuration()),payload).get("status"));assertEquals(0,credentials.get());assertEquals(0,p.creates.get());assertEquals(0,p.sends.get());}String valid="😀"+"é".repeat(126)+"x";var ok=new KafkaTestSupport.FakeProtocol(KafkaTestSupport.Event.ACK);var payload=new LinkedHashMap<>(KafkaTestSupport.payload());payload.put("correlationId",valid);payload.put("valueText","😀");assertEquals("ACKNOWLEDGED",KafkaTestSupport.output(KafkaTestSupport.behavior(ok).create(KafkaTestSupport.configuration()),payload).get("status"));assertEquals(valid,KafkaTestSupport.output(KafkaTestSupport.behavior(new KafkaTestSupport.FakeProtocol(KafkaTestSupport.Event.ACK)).create(KafkaTestSupport.configuration(Map.of("correlationId",valid))),Map.of("version","kafka.produce.v1","valueText","x")).get("correlationId"));assertFalse(java.util.Arrays.equals(KafkaText.utf8("\uD83D\uDE00"),KafkaText.utf8("?")));}
    @Test void apacheClientRevokesUseBeforeAcknowledgingClose() throws Exception {
        AtomicInteger closes=new AtomicInteger();
        @SuppressWarnings("unchecked") org.apache.kafka.clients.producer.Producer<byte[],byte[]> producer=(org.apache.kafka.clients.producer.Producer<byte[],byte[]>)java.lang.reflect.Proxy.newProxyInstance(getClass().getClassLoader(),new Class<?>[]{org.apache.kafka.clients.producer.Producer.class},(proxy,method,args)->{if(method.getName().equals("close")){closes.incrementAndGet();return null;}throw new AssertionError("unexpected producer call: "+method.getName());});
        var protocol=new ApacheKafkaProtocol((properties,timeout)->producer);var attempt=protocol.beginCreate(KafkaTestSupport.profile(),"secret".toCharArray(),100);attempt.establish();KafkaProtocol.Client client=attempt.claim();AtomicInteger revocations=new AtomicInteger();client.close(0,()->{revocations.incrementAndGet();assertThrows(IllegalStateException.class,client::flush);});assertEquals(1,revocations.get());assertEquals(1,closes.get());
    }
    private static KafkaProfile copy(KafkaProfile p,String acks,boolean idem,int retries,int mif,boolean tls){return new KafkaProfile(p.tenant(),p.name(),p.bootstrapServers(),p.clientDnsLookup(),tls,p.saslMechanism(),p.username(),p.credentialRef(),p.clientId(),p.defaultTopic(),p.topics(),p.headers(),p.allowPartition(),p.maxPartition(),p.allowTimestamp(),p.compression(),acks,idem,retries,mif,p.allowAutoCreate(),p.maxConcurrency(),p.maxPerSecond(),p.timeoutMs(),p.maxRecordBytes(),p.bufferMemoryBytes());}
}
