package ai.ravenroot.persistence.postgresql;

import ai.ravenroot.api.persistence.*;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Types;
import java.time.Duration;
import java.time.Instant;
import java.util.ArrayList;
import java.util.List;
import java.util.Optional;
import java.util.UUID;

/** PostgreSQL persistence for saga aggregates and the leased application-command outbox. */
final class PostgresSagaStorage {
    private PostgresSagaStorage() { }

    static void write(Connection c, ExecutionKey key, ExecutionBatch batch, Instant now,
                      SagaOutboxCapacity capacity) throws SQLException {
        if (!batch.sagaCommands().isEmpty()) lockCapacity(c, key.tenantId());
        for (SagaWrite write : batch.sagaWrites()) writeSnapshot(c,key,write);
        for (SagaCommandIntent intent : batch.sagaCommands()) writeIntent(c,key,intent,now,capacity);
        for (UUID messageId : batch.sagaCommandsToRearm()) rearm(c,key,messageId,batch,now);
    }
    private static void writeSnapshot(Connection c,ExecutionKey key,SagaWrite write)throws SQLException{
        SagaSnapshot snapshot=write.snapshot();if(!snapshot.key().equals(key))throw invalid("saga snapshot scope differs from its execution batch");
        try(var s=c.prepareStatement("SELECT revision,snapshot FROM saga_instance WHERE tenant_id=? AND process_instance_id=? AND saga_id=? FOR UPDATE")){bindKey(s,key);s.setObject(3,snapshot.sagaId());try(ResultSet r=s.executeQuery()){
            if(!r.next()){if(write.expectedRevision()!=0||snapshot.revision()!=1)throw conflict(key,0);try(var i=c.prepareStatement("INSERT INTO saga_instance (tenant_id,process_instance_id,saga_id,revision,disposition,graph_completed,snapshot) VALUES (?,?,?,?,?,?,?)")){bindKey(i,key);i.setObject(3,snapshot.sagaId());i.setLong(4,1);i.setString(5,snapshot.disposition().name());i.setBoolean(6,snapshot.graphCompleted());i.setBytes(7,SagaSnapshotCodec.encode(snapshot));i.executeUpdate();}return;}
            long revision=r.getLong(1);SagaSnapshot current=SagaSnapshotCodec.decode(r.getBytes(2));if(revision!=write.expectedRevision()||snapshot.revision()!=revision+1)throw conflict(key,revision);if(!current.definition().equals(snapshot.definition()))throw invalid("a persisted saga definition is immutable");
            try(var u=c.prepareStatement("UPDATE saga_instance SET revision=?,disposition=?,graph_completed=?,snapshot=? WHERE tenant_id=? AND process_instance_id=? AND saga_id=? AND revision=?")){u.setLong(1,snapshot.revision());u.setString(2,snapshot.disposition().name());u.setBoolean(3,snapshot.graphCompleted());u.setBytes(4,SagaSnapshotCodec.encode(snapshot));u.setString(5,key.tenantId());u.setObject(6,key.processInstanceId());u.setObject(7,snapshot.sagaId());u.setLong(8,revision);if(u.executeUpdate()!=1)throw conflict(key,revision);}
        }}
    }
    private static void writeIntent(Connection c,ExecutionKey key,SagaCommandIntent intent,Instant now,SagaOutboxCapacity capacity)throws SQLException{
        byte[] encoded=SagaCommandCodec.encode(intent);try(var s=c.prepareStatement("SELECT message_id,identity_fingerprint,intent FROM saga_command_outbox WHERE tenant_id=? AND (message_id=? OR operation_id=?) FOR UPDATE")){s.setString(1,key.tenantId());s.setObject(2,intent.messageId());s.setString(3,intent.operationId());try(ResultSet r=s.executeQuery()){if(r.next()){if(!r.getObject(1,UUID.class).equals(intent.messageId())||!r.getString(2).equals(intent.identityFingerprint())||!java.util.Arrays.equals(r.getBytes(3),encoded))throw invalid("saga command identity was reused with different content");return;}}}
        ensureCapacity(c,key.tenantId(),encoded.length,capacity);
        try(var i=c.prepareStatement("INSERT INTO saga_command_outbox (tenant_id,process_instance_id,message_id,saga_id,operation_id,identity_fingerprint,intent,status,attempts,owner,fencing_token,lease_expires_at_epoch_second,lease_expires_at_nano,next_attempt_at_epoch_second,next_attempt_at_nano,created_at_epoch_second,created_at_nano,broker_accepted_at_epoch_second,broker_accepted_at_nano,business_completed_at_epoch_second,business_completed_at_nano,last_failure) VALUES (?,?,?,?,?,?,?,?,0,NULL,0,NULL,NULL,?,?,?,?,NULL,NULL,NULL,NULL,'')")){i.setString(1,key.tenantId());i.setObject(2,key.processInstanceId());i.setObject(3,intent.messageId());i.setObject(4,intent.sagaId());i.setString(5,intent.operationId());i.setString(6,intent.identityFingerprint());i.setBytes(7,encoded);i.setString(8,SagaOutboxStatus.PENDING.name());StoredInstant.bindValue(i,9,intent.notBefore());StoredInstant.bindValue(i,11,now);i.executeUpdate();}
    }
    private static void lockCapacity(Connection c,String tenant)throws SQLException{try(var s=c.prepareStatement("SELECT pg_advisory_xact_lock(hashtextextended(?,0))")){s.setString(1,"ravenroot-saga-outbox-capacity:"+tenant);s.execute();}}
    private static void ensureCapacity(Connection c,String tenant,int additionalBytes,SagaOutboxCapacity capacity)throws SQLException{try(var s=c.prepareStatement("SELECT COUNT(*),COALESCE(SUM(OCTET_LENGTH(intent)),0) FROM saga_command_outbox WHERE tenant_id=? AND status NOT IN ('BUSINESS_COMPLETED','EXHAUSTED')")){s.setString(1,tenant);try(ResultSet r=s.executeQuery()){r.next();if(r.getLong(1)+1>capacity.maximumOutstandingCommands()||r.getLong(2)+additionalBytes>capacity.maximumOutstandingBytes())throw invalid("saga outbox tenant capacity exceeded");}}}
    private static void rearm(Connection c,ExecutionKey key,UUID messageId,ExecutionBatch batch,Instant now)throws SQLException{
        try(var s=c.prepareStatement("SELECT saga_id,status,broker_accepted_at_epoch_second FROM saga_command_outbox WHERE tenant_id=? AND process_instance_id=? AND message_id=? FOR UPDATE")){bindKey(s,key);s.setObject(3,messageId);try(ResultSet r=s.executeQuery()){
            if(!r.next()||!SagaOutboxStatus.EXHAUSTED.name().equals(r.getString(2)))throw invalid("only an exhausted command in this execution may be rearmed");
            UUID sagaId=r.getObject(1,UUID.class);if(batch.sagaWrites().stream().noneMatch(write->write.snapshot().sagaId().equals(sagaId)))throw invalid("saga command rearm requires an atomic owning saga write");
            String status=r.getObject(3)==null?SagaOutboxStatus.PENDING.name():SagaOutboxStatus.BROKER_ACCEPTED.name();
            try(var u=c.prepareStatement("UPDATE saga_command_outbox SET status=?,attempts=0,owner=NULL,fencing_token=fencing_token+1,lease_expires_at_epoch_second=NULL,lease_expires_at_nano=NULL,next_attempt_at_epoch_second=?,next_attempt_at_nano=?,last_failure='operator rearmed bounded delivery' WHERE tenant_id=? AND process_instance_id=? AND message_id=? AND status='EXHAUSTED'")){u.setString(1,status);StoredInstant.bindValue(u,2,now);u.setString(4,key.tenantId());u.setObject(5,key.processInstanceId());u.setObject(6,messageId);if(u.executeUpdate()!=1)throw invalid("concurrent saga command rearm");}
        }}
    }
    static Optional<SagaSnapshot> load(Connection c,ExecutionKey key,UUID saga)throws SQLException{try(var s=c.prepareStatement("SELECT snapshot FROM saga_instance WHERE tenant_id=? AND process_instance_id=? AND saga_id=?")){bindKey(s,key);s.setObject(3,saga);try(ResultSet r=s.executeQuery()){return r.next()?Optional.of(SagaSnapshotCodec.decode(r.getBytes(1))):Optional.empty();}}}
    static List<SagaSnapshot> list(Connection c,ExecutionKey key)throws SQLException{try(var s=c.prepareStatement("SELECT snapshot FROM saga_instance WHERE tenant_id=? AND process_instance_id=? ORDER BY saga_id")){bindKey(s,key);try(ResultSet r=s.executeQuery()){var out=new ArrayList<SagaSnapshot>();while(r.next())out.add(SagaSnapshotCodec.decode(r.getBytes(1)));return List.copyOf(out);}}}
    static List<SagaSnapshot> completionCandidates(Connection c,String tenant,int limit,Instant now)throws SQLException{var out=new ArrayList<SagaSnapshot>();try(var s=c.prepareStatement("SELECT s.snapshot FROM saga_instance s LEFT JOIN lease l ON l.tenant_id=s.tenant_id AND l.process_instance_id=s.process_instance_id WHERE s.tenant_id=? AND s.graph_completed=TRUE AND s.disposition IN ('SUCCEEDED','COMPENSATED') AND (l.process_instance_id IS NULL OR (l.expires_at_epoch_second,l.expires_at_nano) <= (?,?)) ORDER BY s.process_instance_id,s.saga_id LIMIT ?")){s.setString(1,tenant);s.setLong(2,now.getEpochSecond());s.setInt(3,now.getNano());s.setInt(4,limit);try(ResultSet r=s.executeQuery()){while(r.next())out.add(SagaSnapshotCodec.decode(r.getBytes(1)));}}return List.copyOf(out);}
    static List<SagaSnapshot> recoveryCandidates(Connection c,String tenant,int limit,Instant now)throws SQLException{var out=new ArrayList<SagaSnapshot>();try(var s=c.prepareStatement("SELECT s.snapshot FROM saga_instance s LEFT JOIN lease l ON l.tenant_id=s.tenant_id AND l.process_instance_id=s.process_instance_id WHERE s.tenant_id=? AND s.disposition NOT IN ('SUCCEEDED','COMPENSATED') AND (l.process_instance_id IS NULL OR (l.expires_at_epoch_second,l.expires_at_nano) <= (?,?)) ORDER BY s.process_instance_id,s.saga_id LIMIT ?")){s.setString(1,tenant);s.setLong(2,now.getEpochSecond());s.setInt(3,now.getNano());s.setInt(4,limit);try(ResultSet r=s.executeQuery()){while(r.next())out.add(SagaSnapshotCodec.decode(r.getBytes(1)));}}return List.copyOf(out);}
    static List<SagaOutboxRecord> listCommands(Connection c,ExecutionKey key)throws SQLException{var out=new ArrayList<SagaOutboxRecord>();try(var s=c.prepareStatement("SELECT * FROM saga_command_outbox WHERE tenant_id=? AND process_instance_id=? ORDER BY message_id")){bindKey(s,key);try(ResultSet r=s.executeQuery()){while(r.next())out.add(record(r,key.tenantId()));}}return List.copyOf(out);}
    static List<SagaOutboxRecord> claim(Connection c,String tenant,String worker,int limit,Duration ttl,Instant now)throws SQLException{
        var ids=new ArrayList<UUID>();try(var s=c.prepareStatement("SELECT message_id FROM saga_command_outbox WHERE tenant_id=? AND status NOT IN ('BUSINESS_COMPLETED','EXHAUSTED') AND attempts < 100 AND (status<>'CLAIMED' OR (lease_expires_at_epoch_second,lease_expires_at_nano) <= (?,?)) AND (next_attempt_at_epoch_second,next_attempt_at_nano) <= (?,?) ORDER BY next_attempt_at_epoch_second,next_attempt_at_nano,message_id FOR UPDATE SKIP LOCKED LIMIT ?")){s.setString(1,tenant);s.setLong(2,now.getEpochSecond());s.setInt(3,now.getNano());s.setLong(4,now.getEpochSecond());s.setInt(5,now.getNano());s.setInt(6,limit);try(ResultSet r=s.executeQuery()){while(r.next())ids.add(r.getObject(1,UUID.class));}}
        var out=new ArrayList<SagaOutboxRecord>();for(UUID id:ids){SagaOutboxRecord previous=read(c,tenant,id);if(previous.attempts()>=previous.intent().maxAttempts()){exhaust(c,previous,"delivery attempts exhausted after recovery",now);continue;}long fence=previous.fencingToken()+1;Instant expiry=now.plus(ttl);try(var u=c.prepareStatement("UPDATE saga_command_outbox SET status='CLAIMED',owner=?,fencing_token=?,lease_expires_at_epoch_second=?,lease_expires_at_nano=?,attempts=attempts+1 WHERE tenant_id=? AND message_id=?")){u.setString(1,worker);u.setLong(2,fence);StoredInstant.bindValue(u,3,expiry);u.setString(5,tenant);u.setObject(6,id);u.executeUpdate();}out.add(read(c,tenant,id));}return List.copyOf(out);
    }
    static SagaOutboxRecord settle(Connection c,String tenant,UUID message,String worker,long fence,SagaOutboxSettlement settlement,Instant now)throws SQLException{
        SagaOutboxRecord current=read(c,tenant,message);if(current.status()!=SagaOutboxStatus.CLAIMED||!worker.equals(current.owner())||current.fencingToken()!=fence)throw invalid("stale saga outbox settlement");String status;Instant next=current.nextAttemptAt(),accepted=current.brokerAcceptedAt(),completed=current.businessCompletedAt();String failure="";
        if(settlement instanceof SagaOutboxSettlement.BrokerAccepted){status="BROKER_ACCEPTED";accepted=now;next=now.plusSeconds(1);}else if(settlement instanceof SagaOutboxSettlement.BusinessCompleted){status="BUSINESS_COMPLETED";completed=now;SagaSnapshot saga=load(c,current.key(),current.intent().sagaId()).orElseThrow(()->invalid("saga disappeared"));writeSnapshot(c,current.key(),new SagaWrite(UUID.randomUUID(),saga.revision(),SagaCommandCompletion.fold(saga,current.intent(),now)));}else if(settlement instanceof SagaOutboxSettlement.Retry retry){status=current.attempts()>=current.intent().maxAttempts()?"EXHAUSTED":current.brokerAcceptedAt()==null?"PENDING":"BROKER_ACCEPTED";next=now.plus(retry.delay());failure=retry.safeReason();if("EXHAUSTED".equals(status))foldExhausted(c,current,failure,now);}else{status="EXHAUSTED";failure=((SagaOutboxSettlement.Exhausted)settlement).safeReason();foldExhausted(c,current,failure,now);}
        try(var u=c.prepareStatement("UPDATE saga_command_outbox SET status=?,owner=NULL,lease_expires_at_epoch_second=NULL,lease_expires_at_nano=NULL,next_attempt_at_epoch_second=?,next_attempt_at_nano=?,broker_accepted_at_epoch_second=?,broker_accepted_at_nano=?,business_completed_at_epoch_second=?,business_completed_at_nano=?,last_failure=? WHERE tenant_id=? AND message_id=? AND owner=? AND fencing_token=?")){u.setString(1,status);StoredInstant.bindValue(u,2,next);bindNullable(u,4,accepted);bindNullable(u,6,completed);u.setString(8,failure);u.setString(9,tenant);u.setObject(10,message);u.setString(11,worker);u.setLong(12,fence);if(u.executeUpdate()!=1)throw invalid("stale saga outbox settlement");}return read(c,tenant,message);
    }
    private static void exhaust(Connection c,SagaOutboxRecord record,String reason,Instant now)throws SQLException{foldExhausted(c,record,reason,now);try(var u=c.prepareStatement("UPDATE saga_command_outbox SET status='EXHAUSTED',owner=NULL,lease_expires_at_epoch_second=NULL,lease_expires_at_nano=NULL,last_failure=? WHERE tenant_id=? AND message_id=?")){u.setString(1,reason);u.setString(2,record.key().tenantId());u.setObject(3,record.intent().messageId());u.executeUpdate();}}
    private static void foldExhausted(Connection c,SagaOutboxRecord record,String reason,Instant now)throws SQLException{SagaSnapshot saga=load(c,record.key(),record.intent().sagaId()).orElseThrow(()->invalid("saga disappeared"));writeSnapshot(c,record.key(),new SagaWrite(UUID.randomUUID(),saga.revision(),SagaCommandCompletion.exhausted(saga,record.intent(),now,reason)));}
    private static SagaOutboxRecord read(Connection c,String tenant,UUID id)throws SQLException{try(var s=c.prepareStatement("SELECT * FROM saga_command_outbox WHERE tenant_id=? AND message_id=? FOR UPDATE")){s.setString(1,tenant);s.setObject(2,id);try(ResultSet r=s.executeQuery()){if(!r.next())throw invalid("unknown saga outbox message");return record(r,tenant);}}}
    private static SagaOutboxRecord record(ResultSet r,String tenant)throws SQLException{return new SagaOutboxRecord(new ExecutionKey(tenant,r.getObject("process_instance_id",UUID.class)),SagaCommandCodec.decode(r.getBytes("intent")),SagaOutboxStatus.valueOf(r.getString("status")),r.getInt("attempts"),r.getString("owner"),r.getLong("fencing_token"),instant(r,"lease_expires_at"),StoredInstant.read(r,"next_attempt_at"),r.getString("last_failure"),StoredInstant.read(r,"created_at"),instant(r,"broker_accepted_at"),instant(r,"business_completed_at"));}
    private static Instant instant(ResultSet r,String prefix)throws SQLException{return r.getObject(prefix+"_epoch_second")==null?null:StoredInstant.read(r,prefix);}
    private static void bindNullable(java.sql.PreparedStatement s,int index,Instant value)throws SQLException{if(value==null){s.setNull(index,Types.BIGINT);s.setNull(index+1,Types.INTEGER);}else StoredInstant.bindValue(s,index,value);}
    private static void bindKey(java.sql.PreparedStatement s,ExecutionKey key)throws SQLException{s.setString(1,key.tenantId());s.setObject(2,key.processInstanceId());}
    private static ExecutionStoreException invalid(String reason){return new ExecutionStoreException(ExecutionStoreFailure.invalid(reason));}
    private static ExecutionStoreException conflict(ExecutionKey key,long actual){return new ExecutionStoreException(new ExecutionStoreFailure.ConcurrencyConflict(key,RevisionExpectation.any(),actual));}
}
