package ai.ravenroot.server.credential;

import ai.ravenroot.api.security.SecretValue;

import java.nio.file.Path;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.time.Clock;
import java.time.Instant;
import java.util.ArrayList;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

/**
 * The author-entered credential store, on disk.
 *
 * <h2>Why SQLite, and why its own file</h2>
 * <p>The same two answers {@code SqliteAssistantConsentStore} gives, and for the same reasons. SQLite
 * because it is what this product already uses for state that must survive a restart, with a driver
 * already on the classpath and settings that make a commit durable. Its own file because the
 * execution store is <b>operationally disposable by design</b> — {@code RAVENROOT_EXECUTION_STORE_ENABLED=false}
 * switches it off and {@code SqliteStoreLocation#restoreFrom} replaces the whole file with a backup —
 * and an author's credentials must not be erased by an operator who meant to stop persisting
 * executions, nor rolled back by one restoring an audit trail.</p>
 *
 * <p>It is also its own file rather than a table beside the consent register, which is the closer
 * call. They are the same age and the same shape. They are separated because they answer to different
 * rules: a consent record is a statement the author can always be asked to make again, while a
 * credential is material the author cannot reconstruct from anything Ravenroot holds. An operator
 * copying one of these two files somewhere less careful should not have taken the other with it.</p>
 *
 * <h2>Stored in clear, and this is the deliberate scope</h2>
 * <p><b>The secret column holds the value as text.</b> Encryption at rest under an operator-managed
 * key, rotation and revocation are outside this store's scope. The protections that actually apply are the file system's and
 * the deployment's — the file lives under {@link #DIRECTORY_VARIABLE}, inside the data volume, and
 * anyone who can read that volume can read every author's credentials.</p>
 *
 * <p>This is written here, in {@link UserCredentialStore}, and in the operator documentation, because
 * a reader who assumes otherwise assumes in the dangerous direction. A key generated by the product
 * and stored beside the database would <em>look</em> like encryption at rest and would protect
 * against nothing this does not: whoever can read the file can read the key. Doing that instead would
 * have been worse than doing nothing, because it would also have been a false claim.</p>
 */
public final class SqliteUserCredentialStore implements UserCredentialStore, AutoCloseable {

    /** Where the store lives. Its own directory, for the reason this class's Javadoc gives. */
    public static final String DIRECTORY_VARIABLE = "RAVENROOT_CREDENTIAL_DIR";

    /**
     * Relative on purpose, and for the container reason {@code SqliteAssistantConsentStore} records:
     * the image sets {@code WORKDIR /opt/ravenroot} and the persistent volume is mounted at
     * {@code /opt/ravenroot/data}, so this resolves inside the volume an operator already backs up.
     * Verified against {@code Dockerfile}, {@code compose.yaml}, {@code deploy/kubernetes/ravenroot.yaml}
     * and the Helm template rather than inferred from convention.
     */
    private static final String DEFAULT_DIRECTORY = "./data/credentials";

    /** Spelled out so two deployments agree on the file without configuring its name. */
    public static final String FILE_NAME = "ravenroot-credentials.db";

    /** The highest schema version this binary knows. A file above it is refused, never opened. */
    private static final int SCHEMA_VERSION = 1;

    private static final String CREATE_TABLE = """
            CREATE TABLE IF NOT EXISTS user_credential (
                reference  TEXT NOT NULL PRIMARY KEY,
                tenant_id  TEXT NOT NULL,
                subject    TEXT NOT NULL,
                label      TEXT NOT NULL,
                scheme     TEXT NOT NULL,
                username   TEXT NOT NULL,
                secret     TEXT NOT NULL,
                created_at TEXT NOT NULL
            ) WITHOUT ROWID
            """;

    /**
     * The owner index. Every read but {@link #resolve} is owner-scoped, so the owner columns are what
     * the query plans should be built around rather than the primary key.
     */
    private static final String CREATE_INDEX =
            "CREATE INDEX IF NOT EXISTS user_credential_owner "
                    + "ON user_credential (tenant_id, subject, created_at)";

    private final Connection connection;
    private final Clock clock;

    private SqliteUserCredentialStore(Connection connection, Clock clock) {
        this.connection = connection;
        this.clock = clock;
    }

    /** The store the operator's environment names, or the default location beside it. */
    public static SqliteUserCredentialStore fromEnvironment(Map<String, String> environment) {
        Objects.requireNonNull(environment, "environment");
        String configured = environment.get(DIRECTORY_VARIABLE);
        Path directory;
        try {
            directory = Path.of(configured == null || configured.isBlank()
                    ? DEFAULT_DIRECTORY : configured.trim());
        } catch (RuntimeException invalidPath) {
            // Deliberately not carrying the cause: an InvalidPathException repeats the raw environment
            // value, and the only useful answer at startup is that this setting is unusable.
            throw new IllegalArgumentException("Invalid credential directory configuration");
        }
        return openUnder(directory);
    }

    /** The store in {@code directory}, creating the directory and the schema if absent. */
    public static SqliteUserCredentialStore openUnder(Path directory) {
        return openUnder(directory, Clock.systemUTC());
    }

    public static SqliteUserCredentialStore openUnder(Path directory, Clock clock) {
        Objects.requireNonNull(directory, "directory");
        Objects.requireNonNull(clock, "clock");
        Path databaseFile = directory.toAbsolutePath().normalize().resolve(FILE_NAME);
        try {
            java.nio.file.Files.createDirectories(databaseFile.getParent());
        } catch (java.io.IOException failed) {
            throw new IllegalStateException(
                    "cannot create the credential directory " + databaseFile.getParent(), failed);
        }
        Connection opened = null;
        try {
            opened = DriverManager.getConnection("jdbc:sqlite:" + databaseFile);
            prepare(opened);
            restrictPermissions(databaseFile);
            return new SqliteUserCredentialStore(opened, clock);
        } catch (SQLException failed) {
            closeQuietly(opened);
            throw new IllegalStateException("cannot open the credential store at " + databaseFile, failed);
        } catch (RuntimeException failed) {
            closeQuietly(opened);
            throw failed;
        }
    }

    /**
     * Narrows the database file to its owner where the platform supports it.
     *
     * <p><b>Best effort, and claimed as nothing more.</b> POSIX permissions are the only protection
     * this store has — see the class comment on encryption at rest — so it is worth setting them, and
     * it is worth being precise that setting them is not a guarantee: a non-POSIX file system, a
     * container running as root with a shared volume, or a backup process copying the file elsewhere
     * all defeat it. A deployment that needs more than this needs the excluded work.</p>
     */
    private static void restrictPermissions(Path databaseFile) {
        try {
            java.nio.file.Files.setPosixFilePermissions(databaseFile,
                    java.util.EnumSet.of(java.nio.file.attribute.PosixFilePermission.OWNER_READ,
                            java.nio.file.attribute.PosixFilePermission.OWNER_WRITE));
        } catch (java.io.IOException | UnsupportedOperationException | SecurityException unsupported) {
            // Not fatal: a store that refused to open on a file system without POSIX permissions
            // would make the feature unavailable on those platforms in exchange for a protection the
            // platform was never going to provide anyway.
        }
    }

    private static void prepare(Connection connection) throws SQLException {
        connection.setAutoCommit(true);
        try (Statement statement = connection.createStatement()) {
            try (ResultSet mode = statement.executeQuery("PRAGMA journal_mode=WAL")) {
                mode.next();
            }
            // FULL rather than NORMAL, the same choice the consent register makes and for a stronger
            // reason: a credential the author was told was saved, lost to a host failure between
            // commit and checkpoint, is a value they may no longer have anywhere else.
            statement.execute("PRAGMA synchronous=FULL");
            statement.execute("PRAGMA busy_timeout=5000");
        }
        int version = userVersion(connection);
        if (version > SCHEMA_VERSION) {
            throw new IllegalStateException("the credential store was written by a newer build "
                    + "(schema version " + version + ", this build knows " + SCHEMA_VERSION + ")");
        }
        if (version < SCHEMA_VERSION) {
            connection.setAutoCommit(false);
            try (Statement statement = connection.createStatement()) {
                statement.execute(CREATE_TABLE);
                statement.execute(CREATE_INDEX);
                statement.execute("PRAGMA user_version = " + SCHEMA_VERSION);
                connection.commit();
            } catch (SQLException failed) {
                connection.rollback();
                throw failed;
            } finally {
                connection.setAutoCommit(true);
            }
        }
    }

    private static int userVersion(Connection connection) throws SQLException {
        try (Statement statement = connection.createStatement();
             ResultSet rows = statement.executeQuery("PRAGMA user_version")) {
            return rows.next() ? rows.getInt(1) : 0;
        }
    }

    @Override
    public StoredCredential mint(String tenantId, String subject, String label,
                                 CredentialScheme scheme, String username, char[] secret) {
        Objects.requireNonNull(tenantId, "tenantId");
        Objects.requireNonNull(subject, "subject");
        Objects.requireNonNull(label, "label");
        Objects.requireNonNull(scheme, "scheme");
        Objects.requireNonNull(secret, "secret");
        String reference = CredentialReference.mint();
        Instant createdAt = clock.instant();
        String storedUsername = scheme.carriesUsername() ? Objects.requireNonNull(username, "username") : "";
        // Materialised as a String because that is what JDBC's setString takes. the secret-handling contract's
        // honest language applies exactly here: this product does not intentionally persist, cache,
        // log or emit secret material anywhere else, and it cannot guarantee erasure of this one.
        String secretText = new String(secret);
        synchronized (connection) {
            try (PreparedStatement insert = connection.prepareStatement(
                    "INSERT INTO user_credential (reference, tenant_id, subject, label, scheme, "
                            + "username, secret, created_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?)")) {
                insert.setString(1, reference);
                insert.setString(2, tenantId);
                insert.setString(3, subject);
                insert.setString(4, label);
                insert.setString(5, scheme.wireValue());
                insert.setString(6, storedUsername);
                insert.setString(7, secretText);
                insert.setString(8, createdAt.toString());
                insert.executeUpdate();
            } catch (SQLException failed) {
                // The cause is not carried outward by the route: several SQLite messages quote the
                // statement, and the statement's parameters are the value. See the caller.
                throw new IllegalStateException("cannot store the credential");
            }
        }
        return new StoredCredential(reference, label, scheme, storedUsername, createdAt);
    }

    @Override
    public List<StoredCredential> listFor(String tenantId, String subject) {
        Objects.requireNonNull(tenantId, "tenantId");
        Objects.requireNonNull(subject, "subject");
        var found = new ArrayList<StoredCredential>();
        synchronized (connection) {
            try (PreparedStatement query = connection.prepareStatement(
                    "SELECT reference, label, scheme, username, created_at FROM user_credential "
                            + "WHERE tenant_id = ? AND subject = ? ORDER BY created_at DESC, reference")) {
                // Owner-scoped listing depends on both predicates in this WHERE clause. Removing
                // `subject` reds UserCredentialStoreTest#oneAuthorNeverSeesAnothersCredentials
                // and CredentialRouteTest#asecondAuthorSeesNothingOfTheFirsts; removing `tenant_id`
                // reds UserCredentialStoreTest#anotherTenantIsAlsoAnotherOwner. Both mutations were
                // run.
                query.setString(1, tenantId);
                query.setString(2, subject);
                try (ResultSet rows = query.executeQuery()) {
                    while (rows.next()) {
                        schemeNamed(rows.getString(3)).ifPresent(scheme -> found.add(new StoredCredential(
                                readString(rows, 1), readString(rows, 2), scheme, readString(rows, 4),
                                Instant.parse(readString(rows, 5)))));
                    }
                }
            } catch (SQLException failed) {
                throw new IllegalStateException("cannot read the credential store");
            }
        }
        return List.copyOf(found);
    }

    @Override
    public boolean isOwnedBy(String reference, String tenantId, String subject) {
        if (reference == null || tenantId == null || subject == null) {
            return false;
        }
        synchronized (connection) {
            try (PreparedStatement query = connection.prepareStatement(
                    "SELECT 1 FROM user_credential WHERE reference = ? AND tenant_id = ? AND subject = ?")) {
                query.setString(1, reference);
                query.setString(2, tenantId);
                query.setString(3, subject);
                try (ResultSet rows = query.executeQuery()) {
                    return rows.next();
                }
            } catch (SQLException failed) {
                // Fail closed. An admission check that answered "allowed" because the database was
                // unreachable would turn an outage into an authorization bypass.
                throw new IllegalStateException("cannot read the credential store");
            }
        }
    }

    @Override
    public Optional<SecretValue> resolve(String reference) {
        if (!CredentialReference.isMinted(reference)) {
            // Not one of ours. Answering empty rather than querying keeps every operator-provisioned
            // reference off this database entirely -- see CredentialReference on why the two
            // namespaces are disjoint by shape.
            return Optional.empty();
        }
        synchronized (connection) {
            try (PreparedStatement query = connection.prepareStatement(
                    "SELECT scheme, username, secret FROM user_credential WHERE reference = ?")) {
                query.setString(1, reference);
                try (ResultSet rows = query.executeQuery()) {
                    if (!rows.next()) {
                        return Optional.empty();
                    }
                    Optional<CredentialScheme> scheme = schemeNamed(rows.getString(1));
                    if (scheme.isEmpty()) {
                        // A row naming a scheme this build no longer has. Empty rather than a guess:
                        // rendering it under the wrong scheme would send a password where a bearer
                        // token was expected.
                        return Optional.empty();
                    }
                    return Optional.of(new SecretValue(
                            render(scheme.get(), rows.getString(2), rows.getString(3)).toCharArray()));
                }
            } catch (SQLException failed) {
                throw new IllegalStateException("cannot read the credential store");
            }
        }
    }

    /** The one place a scheme becomes the single value a consumer receives. See {@link CredentialScheme}. */
    private static String render(CredentialScheme scheme, String username, String secret) {
        return scheme == CredentialScheme.BASIC
                ? (username == null ? "" : username) + ":" + (secret == null ? "" : secret)
                : (secret == null ? "" : secret);
    }

    @Override
    public void close() {
        synchronized (connection) {
            closeQuietly(connection);
        }
    }

    private static String readString(ResultSet rows, int column) {
        try {
            String value = rows.getString(column);
            return value == null ? "" : value;
        } catch (SQLException failed) {
            throw new IllegalStateException("cannot read the credential store");
        }
    }

    private static Optional<CredentialScheme> schemeNamed(String stored) {
        if (stored == null) {
            return Optional.empty();
        }
        try {
            return Optional.of(CredentialScheme.parse(stored.trim().toLowerCase(Locale.ROOT)));
        } catch (IllegalArgumentException unknown) {
            return Optional.empty();
        }
    }

    private static void closeQuietly(Connection connection) {
        if (connection == null) {
            return;
        }
        try {
            connection.close();
        } catch (SQLException ignored) {
            // Nothing a caller can do about a connection that will not close.
        }
    }
}
