package ai.ravenroot.api.application;

/** Closed platform-owned reason vocabulary. Extension source codes use their separately declared registry. */
public enum GraphAdmissionReason {
    GRAPHML_REJECTED,
    INVALID_STRUCTURE,
    DUPLICATE_ELEMENT,
    MISSING_START,
    MISSING_END,
    INVALID_TERMINAL_COUNT,
    DANGLING_EDGE,
    INVALID_PROPERTY,
    REQUIRED_PROPERTY_MISSING,
    PROPERTY_TYPE_INVALID,
    PROPERTY_VALUE_NOT_ALLOWED,
    PROPERTY_OUT_OF_RANGE,
    PROPERTY_TOO_LARGE,
    PROPERTY_COLLECTION_INVALID,
    PROPERTY_NAME_NEAR_MISS,
    RESERVED_PROPERTY,
    WORKSPACE_REFERENCE_INVALID,
    REMOVED_BEHAVIOR,
    CAPABILITY_UNAVAILABLE,
    RUNTIME_NATURE_INVALID,
    RUNTIME_NATURE_NOT_ALLOWED,
    RUNTIME_NATURE_UNSUPPORTED,
    BYPASS_INVALID,
    RUNTIME_CONCURRENCY_INVALID,
    GRAPH_LIMIT_EXCEEDED,
    SOURCE_CAPABILITY_MISMATCH,
    SOURCE_REQUIRED,
    SOURCE_START_REFUSED,
    STARTUP_FAILED
}
