import unittest

from scripts.publish_bundle_reference import Bundle, _published_link, render


class PublishBundleReferenceTest(unittest.TestCase):
    def test_docs_link_is_rebased_and_module_file_is_pinned(self):
        bundle = Bundle("ai", "ai.ravenroot.extensions.ai", ("llm-prompt", "agent"))
        self.assertEqual(
            "../../integrator-guide/ai-programs.md",
            _published_link(bundle, "../../../docs/integrator-guide/ai-programs.md"),
        )
        self.assertEqual(
            "https://github.com/ravenroot-ai/ravenroot/blob/"
            "4aea699ae39b99c8866858ccec0d6531aeb020ea/"
            "ravenroot/ravenroot-extensions/ravenroot-ai/DEPENDENCIES.md",
            _published_link(bundle, "DEPENDENCIES.md"),
        )
        self.assertIn(
            "/blob/dev/"
            "ravenroot/ravenroot-extensions/ravenroot-ai/README.md",
            render(bundle),
        )

    def test_render_names_package_nodes_and_canonical_source(self):
        bundle = Bundle("websocket", "ai.ravenroot.extensions.websocket", (
            "websocket.send", "websocket.receive",
        ))
        published = render(bundle)
        self.assertIn("do not edit this file directly", published)
        self.assertIn("`ai.ravenroot.extensions.websocket`", published)
        self.assertIn("`websocket.send`, `websocket.receive`", published)
        self.assertIn("# WebSocket extension", published)


if __name__ == "__main__":
    unittest.main()
