"""The defence against assistant attribution that does not depend on any tool's settings."""

from __future__ import annotations

import os
import subprocess
import tempfile
import unittest
from pathlib import Path
from unittest import mock

from scripts import check_commit_attribution as check


def git(root: Path, *arguments: str, **env: str) -> str:
    return subprocess.run(["git", *arguments], cwd=root, check=True, capture_output=True, text=True,
                          env={**os.environ, **env}).stdout.strip()


def repository() -> Path:
    root = Path(tempfile.mkdtemp())
    git(root, "init", "-q")
    commit(root, "base", "Person", "person@example.org")
    return root


def commit(root: Path, message: str, name: str, email: str) -> str:
    (root / "file").write_text(message, encoding="utf-8")
    git(root, "add", "file")
    git(root, "commit", "-q", "-m", message, GIT_AUTHOR_NAME=name, GIT_AUTHOR_EMAIL=email,
        GIT_COMMITTER_NAME=name, GIT_COMMITTER_EMAIL=email)
    return git(root, "rev-parse", "HEAD")


class CommitAttributionTest(unittest.TestCase):
    def verdict(self, message: str, name: str = "Polaris", email: str = "agents@ravenroot.ai") -> list[str]:
        root = repository()
        base = git(root, "rev-parse", "HEAD")
        head = commit(root, message, name, email)
        with mock.patch.object(check, "git", side_effect=lambda *a: git(root, *a) + "\n"):
            return [p for sha, author, body in check.commits(base, head) for p in check.problems_in(sha, author, body)]

    def test_a_clean_agent_commit_passes(self) -> None:
        self.assertEqual(self.verdict("Fix the gate\n\nRefs #310"), [])

    def test_an_agent_commit_with_any_co_author_is_refused(self) -> None:
        self.assertTrue(self.verdict("Fix\n\nCo-Authored-By: Claude Opus 5 (1M context) <noreply@anthropic.com>"))
        self.assertTrue(self.verdict("Fix\n\nCo-authored-by: Someone <someone@example.org>"))

    def test_a_tool_address_is_refused_on_anyone_s_commit(self) -> None:
        self.assertTrue(self.verdict("Fix\n\nCo-authored-by: Claude <noreply@anthropic.com>",
                                     name="Person", email="person@example.org"))
        self.assertTrue(self.verdict("Fix\n\nCo-authored-by: Copilot <198982749+Copilot@users.noreply.github.com>",
                                     name="Person", email="person@example.org"))

    def test_people_may_still_credit_each_other(self) -> None:
        self.assertEqual(self.verdict("Fix\n\nCo-authored-by: Colleague <colleague@example.org>",
                                      name="Person", email="person@example.org"), [])

    def test_an_attribution_footer_is_refused(self) -> None:
        self.assertTrue(self.verdict("Fix\n\n🤖 Generated with [Claude Code](https://claude.com/claude-code)"))
        self.assertEqual(self.verdict("Prepare release\n\nGenerated by `scripts/prepare_release.py`."), [])

    def test_the_event_names_the_range_examined(self) -> None:
        self.assertEqual(check.event_range("pull_request", {"pull_request": {"base": {"sha": "b"}, "head": {"sha": "h"}}}),
                         ("b", "h"))
        self.assertEqual(check.event_range("merge_group", {"merge_group": {"base_sha": "b", "head_sha": "h"}}), ("b", "h"))
        self.assertEqual(check.event_range("push", {"before": "b", "after": "h"}), ("b", "h"))
        self.assertIsNone(check.event_range("push", {"before": "0" * 40, "after": "h"}),
                          "a new branch has no before; the checkout's own range is used instead")

    def test_a_force_pushed_before_falls_back_to_the_branch_range(self) -> None:
        """The event's `before` is gone after a force-push; the check must not crash on it."""
        with mock.patch.object(check, "reachable", return_value=False), \
             mock.patch.object(check, "default_range", return_value=("base", "HEAD")) as fallback, \
             mock.patch.object(check, "commits", return_value=[]):
            self.assertEqual(check.main(["--base", "0" * 39 + "1", "--head", "HEAD"]), 0)
        fallback.assert_called_once()


if __name__ == "__main__":
    unittest.main()
