import { writeFile, mkdir, readFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";
import { CONTRACTS, DELIMITED_TEMPLATES, serializeSelection, templateSelection } from "../src/registry.js";
import { validateValue } from "../src/schema.js";
import type { ConfigurationSelection, ValueSchema } from "../src/types.js";

interface Runtime {
  readonly className: string;
  readonly mode: "resolver" | "configuration";
  readonly method?: string;
}

const RUNTIMES: Readonly<Record<string, Runtime>> = {
  "ai.llm-profile": { className: "ai.ravenroot.extensions.ai.EnvironmentLlmProfileResolver", mode: "resolver" },
  "ai.mcp-profile": { className: "ai.ravenroot.extensions.ai.EnvironmentMcpProfileResolver", mode: "resolver" },
  "amqp.profile": { className: "ai.ravenroot.extensions.amqp091.EnvironmentAmqpProfileResolver", mode: "resolver" },
  "amqp.consumer": { className: "ai.ravenroot.extensions.amqp091.EnvironmentAmqpConsumerPolicyResolver", mode: "resolver" },
  "filesystem.profile": { className: "ai.ravenroot.extensions.filesystem.EnvironmentFilesystemProfileResolver", mode: "resolver" },
  "git-workspace.profile": { className: "ai.ravenroot.extensions.gitworkspace.EnvironmentGitWorkspaceProfileResolver", mode: "resolver" },
  "jdbc.profile": { className: "ai.ravenroot.extensions.jdbc.EnvironmentJdbcProfileResolver", mode: "resolver" },
  "kafka.producer-profile": { className: "ai.ravenroot.extensions.kafka.EnvironmentKafkaProfileResolver", mode: "resolver" },
  "kafka.consumer-profile": { className: "ai.ravenroot.extensions.kafka.EnvironmentKafkaConsumerProfileResolver", mode: "resolver" },
  "mail.smtp-profile": { className: "ai.ravenroot.extensions.mail.EnvironmentMailProfileResolver", mode: "resolver" },
  "mail.imap-profile": { className: "ai.ravenroot.extensions.mail.imap.EnvironmentImapProfileResolver", mode: "resolver" },
  "mail.imap-consumer": { className: "ai.ravenroot.extensions.mail.imap.EnvironmentImapConsumerPolicyResolver", mode: "resolver" },
  "mail.imap-mutation": { className: "ai.ravenroot.extensions.mail.imap.EnvironmentImapMutationPolicyResolver", mode: "resolver" },
  "object-storage.profile": { className: "ai.ravenroot.extensions.storage.EnvironmentStorageProfileResolver", mode: "resolver" },
  "ocr.profile": { className: "ai.ravenroot.extensions.ocr.EnvironmentOcrProfileResolver", mode: "resolver" },
  "openapi-client.profile": { className: "ai.ravenroot.extensions.openapi.client.EnvironmentOpenApiClientProfileResolver", mode: "resolver" },
  "openapi-server.config": { className: "ai.ravenroot.extensions.openapi.server.EnvironmentOpenApiServerConfigurationResolver", mode: "resolver" },
  "telegram.profile": { className: "ai.ravenroot.extensions.telegram.EnvironmentTelegramProfileResolver", mode: "resolver" },
  "websocket.profile": { className: "ai.ravenroot.extensions.websocket.EnvironmentWebSocketProfileResolver", mode: "resolver" },
  "discord.config": { className: "ai.ravenroot.extensions.discord.DiscordConfiguration", mode: "configuration", method: "fromEnvironment" },
  "github.config": { className: "ai.ravenroot.extensions.github.GithubConfiguration", mode: "configuration", method: "fromEnvironment" },
  "matrix.config": { className: "ai.ravenroot.extensions.matrix.MatrixConfiguration", mode: "configuration", method: "fromEnvironment" },
  "mattermost.config": { className: "ai.ravenroot.extensions.mattermost.MattermostConfiguration", mode: "configuration", method: "fromEnvironment" },
  "slack.config": { className: "ai.ravenroot.extensions.slack.SlackConfiguration", mode: "configuration", method: "fromEnvironment" },
  "teams.config": { className: "ai.ravenroot.extensions.teams.TeamsConfiguration", mode: "configuration", method: "fromEnvironment" }
};

function property(value: string): string {
  return value.replaceAll("\\", "\\\\").replaceAll("\n", "\\n").replaceAll("\r", "\\r").replaceAll("=", "\\=").replaceAll(":", "\\:");
}

const lines = ["# Generated by ravenroot-configurator/scripts/java-fixtures.ts. Do not edit.", `ids=${Object.keys(RUNTIMES).join(",")}`];

interface Mutation { readonly value: unknown; readonly label: string }

function distinctValidValues(schema: ValueSchema, seed: unknown, count: number): unknown[] {
  const result: unknown[] = [];
  const seen = new Set<string>();
  const add = (candidate: unknown): void => {
    try { validateValue(schema, candidate); } catch { return; }
    const encoded = JSON.stringify(candidate);
    if (!seen.has(encoded)) { seen.add(encoded); result.push(candidate); }
  };
  add(seed);
  if (schema.kind === "string") {
    if (schema.allowed) schema.allowed.forEach(add);
    for (let index = 0; result.length < count && index < count * 4; index++) {
      const suffix = index.toString(36);
      if (schema.format === "sha256") add(index.toString(16).padStart(64, "0"));
      else if (schema.format === "base64") add(Buffer.from(`fixture-${index}`, "utf8").toString("base64"));
      else if (schema.format === "uri" && typeof seed === "string") {
        try { const uri = new URL(seed); uri.searchParams.set("rrFixture", suffix); add(uri.toString()); } catch {}
      } else if (schema.format === "absolute-path") add(`/fixture-${suffix}`);
      else {
        const available = Math.max(0, (schema.maximumLength ?? 4096) - suffix.length);
        add(`${typeof seed === "string" ? seed.slice(0, available) : "x"}${suffix}`);
        add(`x${suffix}`);
      }
    }
  } else if (schema.kind === "integer") {
    const minimum = schema.minimum ?? 0;
    const maximum = schema.maximum ?? Number.MAX_SAFE_INTEGER;
    for (let candidate = minimum; result.length < count && candidate <= maximum; candidate++) add(candidate);
  } else if (schema.kind === "boolean") {
    add(false); add(true);
  } else if (schema.kind === "null") add(null);
  else if (schema.kind === "nullable") {
    add(null);
    distinctValidValues(schema.value, seed, count).forEach(add);
  } else if (schema.kind === "union") {
    for (const choice of schema.choices) distinctValidValues(choice, seed, count).forEach(add);
  } else if (schema.kind === "object" && seed && typeof seed === "object" && !Array.isArray(seed)) {
    for (const [key, childSchema] of Object.entries(schema.properties)) {
      const childSeed = (seed as Record<string, unknown>)[key];
      if (childSeed === undefined) continue;
      for (const childValue of distinctValidValues(childSchema, childSeed, count)) add({ ...(seed as Record<string, unknown>), [key]: childValue });
      if (result.length >= count) break;
    }
  } else if (schema.kind === "map" && seed && typeof seed === "object" && !Array.isArray(seed)) {
    const entries = Object.entries(seed as Record<string, unknown>);
    if (entries.length) {
      const [key, childSeed] = entries[0]!;
      for (const childValue of distinctValidValues(schema.values, childSeed, count)) add({ ...(seed as Record<string, unknown>), [key]: childValue });
    }
  } else if (schema.kind === "array" && Array.isArray(seed) && seed.length) {
    for (const childValue of distinctValidValues(schema.items, seed[0], count)) add([childValue, ...seed.slice(1)]);
  }
  return result.slice(0, count);
}

function boundaryMutations(schema: ValueSchema, value: unknown, path = "document"): Mutation[] {
  const result: Mutation[] = [];
  if (schema.kind === "integer" && typeof value === "number") {
    if (schema.minimum !== undefined) result.push({ value: schema.minimum - 1, label: `${path}:minimum` });
    // MAX_SAFE_INTEGER is the browser representation ceiling for Java long fields, not a
    // resolver ceiling. There is no exact JSON number above it that the UI can round-trip.
    if (schema.maximum !== undefined && schema.maximum < Number.MAX_SAFE_INTEGER) result.push({ value: schema.maximum + 1, label: `${path}:maximum` });
  }
  if (schema.kind === "string" && typeof value === "string") {
    if (schema.minimumLength !== undefined && schema.minimumLength > 0) result.push({ value: "", label: `${path}:minimumLength` });
    if (schema.maximumLength !== undefined) result.push({ value: "x".repeat(schema.maximumLength + 1), label: `${path}:maximumLength` });
    if (schema.allowed) result.push({ value: "not-an-allowed-value", label: `${path}:allowed` });
    if (schema.pattern) result.push({ value: " ", label: `${path}:pattern` });
    if (schema.nonBlank) result.push({ value: "   ", label: `${path}:nonBlank` });
    if (schema.schemes) result.push({ value: `ftp://${new URL(value).host}/invalid`, label: `${path}:scheme` });
    if (schema.allowFragment === false && schema.format === "uri") result.push({ value: `${value}#fragment`, label: `${path}:fragment` });
    if (schema.authorityOnly && schema.format === "uri") {
      const uri = new URL(value); uri.pathname = "/not-an-authority";
      result.push({ value: uri.toString(), label: `${path}:authority-path` });
      uri.pathname = ""; uri.search = "?unexpected=true";
      result.push({ value: uri.toString(), label: `${path}:authority-query` });
    }
    if (schema.format === "duration") result.push({ value: "PT0S", label: `${path}:positive-duration` });
    if (schema.format === "sha256") result.push({ value: "A".repeat(64), label: `${path}:sha256` });
    if (schema.format === "base64") result.push({ value: "not base64", label: `${path}:base64` });
  }
  const child = (childSchema: ValueSchema, childValue: unknown, childPath: string, replace: (replacement: unknown) => unknown): void => {
    for (const mutation of boundaryMutations(childSchema, childValue, childPath)) result.push({ value: replace(mutation.value), label: mutation.label });
  };
  if (schema.kind === "object" && value && typeof value === "object" && !Array.isArray(value)) {
    const optional = new Set(schema.optional ?? []);
    for (const key of Object.keys(schema.properties)) if (!optional.has(key) && key in (value as Record<string, unknown>)) {
      const copy = { ...(value as Record<string, unknown>) }; delete copy[key];
      result.push({ value: copy, label: `${path}.${key}:required` });
    }
    for (const [key, childSchema] of Object.entries(schema.properties)) if (key in (value as Record<string, unknown>)) {
      child(childSchema, (value as Record<string, unknown>)[key], `${path}.${key}`,
        (replacement) => ({ ...(value as Record<string, unknown>), [key]: replacement }));
    }
  }
  if (schema.kind === "map" && value && typeof value === "object" && !Array.isArray(value)) {
    const record = value as Record<string, unknown>; const entries = Object.entries(record);
    if (schema.minimumEntries !== undefined && entries.length < schema.minimumEntries) throw new Error(`${path} fixture does not meet minimumEntries`);
    if (schema.minimumEntries !== undefined && schema.minimumEntries > 0) result.push({ value: {}, label: `${path}:minimumEntries` });
    if (schema.keyPattern && entries.length) result.push({ value: { ...record, "": entries[0]![1] }, label: `${path}:keyPattern` });
    if (schema.maximumEntries !== undefined && entries.length) {
      const expanded: Record<string, unknown> = {};
      for (let index = 0; index <= schema.maximumEntries; index++) expanded[`entry-${index}`] = structuredClone(entries[0]![1]);
      result.push({ value: expanded, label: `${path}:maximumEntries` });
    }
    for (const [key, item] of Object.entries(value as Record<string, unknown>)) child(schema.values, item, `${path}.${key}`,
      (replacement) => ({ ...(value as Record<string, unknown>), [key]: replacement }));
  }
  if (schema.kind === "array" && Array.isArray(value)) {
    if (schema.minimumItems !== undefined && schema.minimumItems > 0) result.push({ value: [], label: `${path}:minimumItems` });
    if (schema.maximumItems !== undefined && value.length) {
      const items = distinctValidValues(schema.items, value[0], schema.maximumItems + 1);
      if (items.length > schema.maximumItems) result.push({ value: items, label: `${path}:maximumItems` });
    }
    value.forEach((item, index) => child(schema.items, item, `${path}[${index}]`, (replacement) => { const copy = [...value]; copy[index] = replacement; return copy; }));
  }
  if (schema.kind === "nullable" && value !== null) child(schema.value, value, path, (replacement) => replacement);
  if (schema.kind === "union") for (const choice of schema.choices) { try { validateValue(choice, value); child(choice, value, path, (replacement) => replacement); break; } catch {} }
  return result;
}

for (const [id, runtime] of Object.entries(RUNTIMES)) {
  const contract = CONTRACTS.find((candidate) => candidate.id === id);
  if (!contract) throw new Error(`Java runtime fixture names unknown contract ${id}`);
  const selection = templateSelection(id);
  if (DELIMITED_TEMPLATES[id]) (selection as unknown as { values: Readonly<Record<string, unknown>> }).values = DELIMITED_TEMPLATES[id]!;
  const serialized = serializeSelection(selection);
  const [environmentKey, valid] = Object.entries(serialized)[0]!;
  const negatives: { value: string; args: string; label: string }[] = [];
  if (contract.encoding === "base64-json") {
    const document = structuredClone(selection.values.document) as Record<string, unknown>;
    document.unsupportedByRuntime = true;
    negatives.push({ value: Buffer.from(JSON.stringify(document), "utf8").toString("base64"), args: "", label: "unknown-field" });
    const mutations = boundaryMutations(contract.schema!, selection.values.document);
    if (contract.crossFieldRules?.includes("credential-pair")) {
      const candidate = structuredClone(selection.values.document) as Record<string, unknown>;
      delete candidate["credentialReference" in candidate ? "credentialReference" : "credentialUsername"];
      mutations.push({ value: candidate, label: "cross-field:credential-pair" });
    }
    if (contract.crossFieldRules?.includes("mcp-tools-bound")) mutations.push({ value: { ...(selection.values.document as object), maxDiscoveredTools: 1, allowedTools: ["search", "lookup"] }, label: "cross-field:mcp-tools-bound" });
    if (contract.crossFieldRules?.includes("jdbc-total-cell")) mutations.push({ value: { ...(selection.values.document as object), maxTotalBytes: 1 }, label: "cross-field:jdbc-total-cell" });
    if (contract.crossFieldRules?.includes("storage-virtual-host")) mutations.push({ value: { ...(selection.values.document as object), addressingStyle: "virtual-hosted" }, label: "cross-field:storage-virtual-host" });
    if (id === "matrix.config") {
      const candidate = structuredClone(selection.values.document) as { profiles: Record<string, { limits: Record<string, unknown> }> };
      const profile = Object.values(candidate.profiles)[0]!;
      profile.limits.requestTimeoutMs = profile.limits.pollTimeoutMs;
      mutations.push({ value: candidate, label: "cross-field:matrix-poll-timeout" });
    }
    for (const mutation of mutations) {
      const invalidSelection = structuredClone(selection) as { values: { document: unknown } }; invalidSelection.values.document = mutation.value;
      try { serializeSelection(invalidSelection); throw new Error(`${id} schema accepted generated negative ${mutation.label}`); } catch (error) {
        if (error instanceof Error && error.message.includes("schema accepted generated negative")) throw error;
      }
      negatives.push({ value: Buffer.from(JSON.stringify(mutation.value), "utf8").toString("base64"), args: "", label: mutation.label });
    }
  } else {
    negatives.push({ value: `${valid};unsupported`, args: "", label: "field-count" });
    contract.fields.forEach((field, index) => {
      const additions: string[] = [];
      if (field.minimum !== undefined) additions.push(String(field.minimum - 1));
      if (field.maximum !== undefined) additions.push(String(field.maximum + 1));
      if (field.allowed) additions.push("not-an-allowed-value");
      if (field.required && !field.allowEmpty && field.type === "string") additions.push("");
      for (const replacement of additions) { const parts = valid.split(contract.delimiter ?? ";"); parts[index] = replacement; negatives.push({ value: parts.join(contract.delimiter ?? ";"), args: "", label: `${field.name}:boundary` }); }
    });
    const crossMutations: { readonly values: Readonly<Record<string, unknown>>; readonly label: string }[] = [];
    if (id === "kafka.producer-profile") {
      crossMutations.push(
        { values: { bufferMemoryBytes: 64, maxRecordBytes: 65 }, label: "cross-field:buffer-record" },
        { values: { idempotence: false }, label: "cross-field:idempotence" },
        { values: { tls: false, bootstrapServers: "broker.example.test:9092" }, label: "cross-field:plaintext-loopback" }
      );
    }
    if (id === "kafka.consumer-profile") {
      crossMutations.push(
        { values: { topics: [], anchoredTopicPattern: "" }, label: "cross-field:subscription-missing" },
        { values: { topics: ["events"], anchoredTopicPattern: "^events$" }, label: "cross-field:subscription-ambiguous" },
        { values: { maxPollIntervalMs: 3000, sessionTimeoutMs: 3000 }, label: "cross-field:session-poll" },
        { values: { sessionTimeoutMs: 3000, heartbeatIntervalMs: 1001 }, label: "cross-field:heartbeat-session" },
        { values: { maxFetchBytes: 100, maxPartitionFetchBytes: 101 }, label: "cross-field:partition-fetch" },
        { values: { maxPartitionFetchBytes: 100, maxRecordBytes: 101 }, label: "cross-field:record-fetch" },
        { values: { maxRecordBytes: 100, maxKeyBytes: 101 }, label: "cross-field:key-record" },
        { values: { maxRecordBytes: 100, maxValueBytes: 101 }, label: "cross-field:value-record" },
        { values: { maxRecordBytes: 100, maxHeaderBytes: 101 }, label: "cross-field:header-record" },
        { values: { retryBackoffMs: 101, maxRetryBackoffMs: 100 }, label: "cross-field:retry-backoff" },
        { values: { poisonPolicy: "dead-letter", deadLetterTopic: "" }, label: "cross-field:dead-letter-required" },
        { values: { topics: ["events"], deadLetterTopic: "events" }, label: "cross-field:dead-letter-overlap" },
        { values: { tls: false, bootstrapServers: "broker.example.test:9092" }, label: "cross-field:plaintext-loopback" }
      );
    }
    for (const mutation of crossMutations) {
      const values = { ...selection.values, ...mutation.values };
      const invalidSelection = { ...selection, values };
      try { serializeSelection(invalidSelection); throw new Error(`${id} schema accepted generated negative ${mutation.label}`); } catch (error) {
        if (error instanceof Error && error.message.includes("schema accepted generated negative")) throw error;
      }
      const value = contract.fields.map((field) => {
        const member = values[field.name];
        return Array.isArray(member) ? member.join(",") : String(member ?? "");
      }).join(contract.delimiter ?? ";");
      negatives.push({ value, args: "", label: mutation.label });
    }
  }
  const args = contract.identity.map((axis) => selection.identity[axis] ?? "").join("\u001f");
  let alternateValid = "";
  if (contract.encoding === "base64-json" && contract.schema?.kind === "object" && contract.schema.optional?.length) {
    const document = structuredClone(selection.values.document) as Record<string, unknown>;
    for (const key of contract.schema.optional) delete document[key];
    alternateValid = Buffer.from(JSON.stringify(document), "utf8").toString("base64");
  }
  for (const negative of negatives) negative.args = args;
  contract.identity.forEach((axis, invalidIndex) => {
    const tooLong = contract.identity.map((candidate, index) => index === invalidIndex ? "x".repeat(65) : selection.identity[candidate] ?? "").join("\u001f");
    const malformed = contract.identity.map((candidate, index) => index === invalidIndex ? "!invalid" : selection.identity[candidate] ?? "").join("\u001f");
    negatives.push({ value: valid, args: tooLong, label: `identity.${axis}:maximumLength` });
    negatives.push({ value: valid, args: malformed, label: `identity.${axis}:pattern` });
  });
  for (const [key, value] of Object.entries({
    class: runtime.className, mode: runtime.mode, method: runtime.method ?? "resolve", args,
    environmentKey, valid, alternateValid, negativeCount: String(negatives.length)
  })) lines.push(`${id}.${key}=${property(value)}`);
  negatives.forEach((negative, index) => {
    lines.push(`${id}.negative.${index}.value=${property(negative.value)}`,
      `${id}.negative.${index}.args=${property(negative.args)}`,
      `${id}.negative.${index}.label=${property(negative.label)}`);
  });
}
const coreIds = ["bundle.service-grant", "core.http", "core.program", "core.human-task", "core.publication-policies", "core.runner"];
lines.push(`core.ids=${coreIds.join(",")}`);
const runnerExample = JSON.parse(await readFile(fileURLToPath(new URL("../../docs/examples/governed-runner/control-plane.json", import.meta.url)), "utf8")) as Record<string, unknown>;
const resolveFixtureSecrets = (value: unknown): unknown => {
  if (Array.isArray(value)) return value.map(resolveFixtureSecrets);
  if (value && typeof value === "object") {
    const entries = Object.entries(value as Record<string, unknown>);
    if (entries.length === 1 && entries[0]?.[0] === "$secret") return Buffer.alloc(32).toString("base64");
    return Object.fromEntries(entries.map(([key, item]) => [key, resolveFixtureSecrets(item)]));
  }
  return value;
};
for (const id of coreIds) {
  const selection = templateSelection(id) as ConfigurationSelection & { values: Record<string, unknown> };
  const templateDocument = selection.values.runnerDocument;
  if (id === "core.runner") selection.values.runnerDocument = runnerExample;
  const environment = serializeSelection(selection);
  lines.push(`core.${id}.environment=${property(Buffer.from(JSON.stringify(environment), "utf8").toString("base64"))}`);
  lines.push(`core.${id}.environmentKeys=${property(Object.keys(environment).join(","))}`);
  for (const [key, value] of Object.entries(environment)) lines.push(`core.${id}.env.${key}=${property(value)}`);
  const negativeEnvironments: { readonly environment: Readonly<Record<string, string>>; readonly label: string }[] = [];
  if (id === "bundle.service-grant") {
    const key = Object.keys(environment)[0]!;
    const document = { ...(selection.values.document as Record<string, unknown>), unsupportedByRuntime: true };
    lines.push(`core.${id}.invalidEnvironmentKey=${property(key)}`,
      `core.${id}.invalidEnvironmentValue=${property(Buffer.from(JSON.stringify(document), "utf8").toString("base64"))}`);
    const contract = CONTRACTS.find((candidate) => candidate.id === id)!;
    for (const mutation of boundaryMutations(contract.schema!, selection.values.document, `${id}.document`)) {
      const invalid = { ...selection, values: { document: mutation.value } };
      try { serializeSelection(invalid); throw new Error(`${id} schema accepted generated negative ${mutation.label}`); }
      catch (error) { if (error instanceof Error && error.message.includes("schema accepted generated negative")) throw error; }
      negativeEnvironments.push({ environment: { [key]: Buffer.from(JSON.stringify(mutation.value), "utf8").toString("base64") }, label: mutation.label });
    }
    negativeEnvironments.push({ environment: { [key]: Buffer.from(JSON.stringify(document), "utf8").toString("base64") }, label: "unknown-field" });
  } else if (id === "core.http") {
    lines.push(`core.${id}.invalidEnvironmentKey=RAVENROOT_HTTP_ALLOWED_PORTS`, `core.${id}.invalidEnvironmentValue=70000`);
    for (const [value, label] of [["0", "ports:minimum"], ["65536", "ports:maximum"], ["not-a-port", "ports:integer"], ["0", "max-request:minimum"], ["0", "max-response:minimum"]] as const) {
      const key = label.startsWith("ports") ? "RAVENROOT_HTTP_ALLOWED_PORTS" : label.startsWith("max-request") ? "RAVENROOT_HTTP_MAX_REQUEST_BYTES" : "RAVENROOT_HTTP_MAX_RESPONSE_BYTES";
      negativeEnvironments.push({ environment: { ...environment, [key]: value }, label });
    }
  } else if (id === "core.program") {
    lines.push(`core.${id}.invalidEnvironmentKey=RAVENROOT_PROGRAM_RUNTIME`, `core.${id}.invalidEnvironmentValue=unknown`);
    for (const [key, value, label] of [
      ["RAVENROOT_PROGRAM_RUNTIME", "unknown", "runtime:allowed"],
      ["RAVENROOT_PROGRAM_TIMEOUT_MS", "99", "timeout:minimum"], ["RAVENROOT_PROGRAM_TIMEOUT_MS", "300001", "timeout:maximum"],
      ["RAVENROOT_PROGRAM_MAX_HEAP_MB", "31", "heap:minimum"], ["RAVENROOT_PROGRAM_MAX_HEAP_MB", "1025", "heap:maximum"]
    ] as const) negativeEnvironments.push({ environment: { ...environment, [key]: value }, label });
  }
  lines.push(`core.${id}.negativeEnvironmentCount=${negativeEnvironments.length}`);
  negativeEnvironments.forEach((negative, index) => {
    lines.push(`core.${id}.negativeEnvironment.${index}.keys=${property(Object.keys(negative.environment).join(","))}`,
      `core.${id}.negativeEnvironment.${index}.label=${property(negative.label)}`);
    for (const [key, value] of Object.entries(negative.environment)) lines.push(
      `core.${id}.negativeEnvironment.${index}.env.${key}=${property(value)}`);
  });
  const document = selection.values.interactionDocument ?? selection.values.policyDocument ?? selection.values.runnerDocument;
  if (document) {
    const resolved = resolveFixtureSecrets(document) as Record<string, unknown>;
    lines.push(`core.${id}.document=${property(Buffer.from(JSON.stringify(resolved), "utf8").toString("base64"))}`);
    if (id === "core.runner" && templateDocument) {
      const alternate = resolveFixtureSecrets(templateDocument);
      lines.push(`core.${id}.alternateDocument=${property(Buffer.from(JSON.stringify(alternate), "utf8").toString("base64"))}`);
    }
    if (id === "core.human-task") {
      const custom = structuredClone(document) as { profiles: Record<string, unknown>[] };
      custom.profiles = [{ id: "custom-review", version: 1, kind: "CUSTOM", launchUri: "https://custom.example.test/task", origin: "https://custom.example.test" }];
      const accepted = { ...selection, values: { ...selection.values, interactionDocument: custom } }; serializeSelection(accepted);
      lines.push(`core.${id}.alternateDocument=${property(Buffer.from(JSON.stringify(resolveFixtureSecrets(custom)), "utf8").toString("base64"))}`);
    }
    const field = CONTRACTS.find((contract) => contract.id === id)?.fields.find((candidate) => candidate.schema);
    if (!field?.schema) throw new Error(`${id} has no explicit core document schema`);
    const mutations = boundaryMutations(field.schema, document, `${id}.document`)
      .filter((mutation) => !mutation.label.includes(".$secret:"));
    mutations.push({ value: { ...(document as object), unsupportedByRuntime: true }, label: `${id}.document:unknown-field` });
    if (id === "core.human-task") {
      const mismatch = structuredClone(document) as { profiles: Record<string, unknown>[] };
      mismatch.profiles[0] = { ...mismatch.profiles[0], origin: "https://different.example.test" };
      mutations.push({ value: mismatch, label: "cross-field:human-task-origin" });
      const shortSecret = structuredClone(document) as { capabilitySecretBase64: unknown };
      shortSecret.capabilitySecretBase64 = "c2hvcnQ=";
      mutations.push({ value: shortSecret, label: "core.human-task.document.capabilitySecretBase64:decoded-minimum" });
    }
    if (id === "core.publication-policies") {
      const pair = structuredClone(document) as { policies: { rules: Record<string, unknown>[] }[] };
      const rule = pair.policies[0]!.rules.find((candidate) => candidate.type === "required-file-pair")!;
      rule.requiredSuffix = rule.firstSuffix;
      mutations.push({ value: pair, label: "cross-field:publication-file-pair" });
    }
    if (id === "core.runner") {
      const storage = structuredClone(document) as { tenants: Record<string, { workspaceProfiles: { capacity: Record<string, unknown>; policy: { limits: Record<string, unknown> } }[] }> };
      const workspace = Object.values(storage.tenants)[0]!.workspaceProfiles[0]!;
      workspace.capacity.aggregateStorageBytes = Number(workspace.policy.limits.workspaceBytes) - 1;
      mutations.push({ value: storage, label: "cross-field:runner-workspace-storage" });
      const skill = structuredClone(document) as { tenants: Record<string, { definitions: { skillInstructions: Record<string, string> }[] }> };
      Object.values(skill.tenants)[0]!.definitions[0]!.skillInstructions = { unapproved: "body" };
      mutations.push({ value: skill, label: "cross-field:runner-skill-body" });
    }
    const negativeDocuments: Mutation[] = [];
    for (const mutation of mutations) {
      const valueName = id === "core.human-task" ? "interactionDocument" : id === "core.publication-policies" ? "policyDocument" : "runnerDocument";
      const invalidSelection = { ...selection, values: { ...selection.values, [valueName]: mutation.value } };
      try { serializeSelection(invalidSelection); throw new Error(`${id} schema accepted generated negative ${mutation.label}`); }
      catch (error) { if (error instanceof Error && error.message.includes("schema accepted generated negative")) throw error; }
      negativeDocuments.push(mutation);
    }
    lines.push(`core.${id}.negativeDocumentCount=${negativeDocuments.length}`);
    negativeDocuments.forEach((negative, index) => lines.push(
      `core.${id}.negativeDocument.${index}.value=${property(Buffer.from(JSON.stringify(resolveFixtureSecrets(negative.value)), "utf8").toString("base64"))}`,
      `core.${id}.negativeDocument.${index}.label=${property(negative.label)}`));
  }
}
const content = `${lines.join("\n")}\n`;
if (process.argv.includes("--write")) {
  const output = process.argv[process.argv.indexOf("--write") + 1];
  if (!output) throw new Error("--write requires an output path");
  const destination = resolve(output);
  await mkdir(dirname(destination), { recursive: true });
  await writeFile(destination, content);
  process.stdout.write(`wrote ${destination}\n`);
} else {
  process.stdout.write(`Java resolver fixtures valid: ${Object.keys(RUNTIMES).length} contracts\n`);
}
