#!/usr/bin/env python3
"""Publish the runtime descriptor snapshot as the complete node-field reference."""

from __future__ import annotations

import argparse
import csv
import re
from collections import OrderedDict
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "docs/reference/node-descriptor-contracts.tsv"
OUTPUT = ROOT / "docs/reference/node-contracts.md"
CORE = {"log", "delay", "human-task", "template", "json-parse", "cel-transform",
        "cel-decision", "json-path", "http-request", "program", "boundary-guard"}
BUNDLES = {
    "llm-prompt": "ai", "agent": "ai", "amqp.publish": "amqp091", "amqp.consume": "amqp091",
    "discord.send": "discord", "discord.interactions": "discord", "filesystem.read": "filesystem",
    "filesystem.write": "filesystem", "git-workspace": "git-workspace",
    "github-events-source": "github", "project-transition": "github", "github-app-review": "github",
    "github-workflow-watch": "github", "release-prepare": "github", "jdbc.query": "jdbc",
    "jdbc.insert": "jdbc", "kafka.produce": "kafka", "kafka.consume": "kafka",
    "mail.send": "mail", "mail.imap.query": "mail", "mail.imap.consume": "mail",
    "mail.imap.move": "mail", "mail.imap.delete": "mail", "object.get": "object-storage",
    "object.put": "object-storage", "object.list": "object-storage", "object.delete": "object-storage",
    "ocr.extract": "ocr", "openapi.call": "openapi-client", "openapi.receive": "openapi-server",
    "openapi.request-reply": "openapi-server", "slack.events": "slack", "slack.commands": "slack",
    "slack.post-message": "slack", "spel.transform": "spel", "spel.decision": "spel",
    "telegram.send": "telegram", "telegram.answer.callback": "telegram",
    "telegram.edit.message": "telegram", "telegram.delete.message": "telegram",
    "websocket.send": "websocket", "websocket.receive": "websocket",
}
TEMPLATE_LITERAL = re.compile(r"\{\{[^{}\n]+\}\}")


def display(value: str, *, zero_is_none: bool = False) -> str:
    if value == "—":
        return value
    if not value or (zero_is_none and value == "0"):
        return "Not declared"
    rendered = value.replace("|", "\\|")
    return TEMPLATE_LITERAL.sub(
        lambda match: "<code>{% raw %}" + match.group(0) + "{% endraw %}</code>",
        rendered,
    )


def constraint(row: dict[str, str]) -> str:
    parts: list[str] = []
    if row["minimum"]:
        parts.append(f"min {row['minimum']}")
    if row["maximum"]:
        parts.append(f"max {row['maximum']}")
    if row["maximumUtf8Bytes"] != "0":
        parts.append(f"max UTF-8 bytes {row['maximumUtf8Bytes']}")
    if row["maximumItems"] != "0":
        parts.append(f"max items {row['maximumItems']}")
    if row["maximumItemUtf8Bytes"] != "0":
        parts.append(f"max item UTF-8 bytes {row['maximumItemUtf8Bytes']}")
    return "; ".join(parts) or "Not declared"


def reference(behavior: str) -> str:
    if behavior in CORE:
        return "[core behavior reference](core-nodes.md)"
    return f"[{BUNDLES[behavior]} bundle reference](bundles/{BUNDLES[behavior]}.md)"


def anchor(behavior: str) -> str:
    return "node-" + behavior.replace(".", "-")


def render() -> str:
    grouped: OrderedDict[str, list[dict[str, str]]] = OrderedDict()
    with SOURCE.open(encoding="utf-8", newline="") as source:
        for row in csv.DictReader(source, delimiter="\t"):
            grouped.setdefault(row["behavior"], []).append(row)
    if set(grouped) != CORE | set(BUNDLES):
        missing = sorted((CORE | set(BUNDLES)) - set(grouped))
        extra = sorted(set(grouped) - (CORE | set(BUNDLES)))
        raise SystemExit(f"node inventory mismatch: missing={missing}, extra={extra}")
    out = ["---", "title: Node descriptor contracts", "---", "",
           "# Node descriptor contracts", "",
           "This page publishes every field exposed by the runtime descriptor catalog at baseline ",
           "`f58cd7c7d98cd370c89199829d5436c6a7e8eb8b`. The checked-in TSV is generated by ",
           "`PublishedNodeContractTest` from compiled Java descriptors; the same test parses and schema-checks ",
           "one complete GraphML file for every node. Regenerate deliberately with:", "",
           "```sh", "cd ravenroot", "mvn -pl ravenroot-extensions/ravenroot-extensions-all -am -DskipTests install",
           "mvn -f ../scripts/fixtures/node-contracts/pom.xml \\",
           "  -Dravenroot.docs.update=true -Dtest=PublishedNodeContractTest test", "cd ..",
           "python3 scripts/publish_node_contract_reference.py", "```", "",
           "> The table records catalog metadata and the admission checks driven by it. A blank descriptor ",
           "> field means **not declared**, not unlimited and not unsupported. A behavior can apply a stricter ",
           "> default or ceiling in code or an operator profile. Follow each node's canonical behavior reference ",
           "> for those behavior-only rules. An empty descriptor outcome means the descriptor does not declare ",
           "> outcomes; it does not prove that the behavior emits none. The complete examples route `continue` ",
           "> in that compatibility case and always include a separate failure route.", "",
           "The Human Task rows show the production descriptor when its durable store supports confirmation ",
           "admission. A store without that capability omits every `confirmation*` field and the ",
           "`embedded-confirmation-v1` capability; the Java gate assembles and asserts both variants. The agent ",
           "rows include all eight catalog skill slots and their visibility conditions.", "",
           "For profile-controlled limits, omission inherits the profile ceiling and an invalid override is ",
           "refused rather than clamped. OpenAPI server properties distinguish an omitted property from an ",
           "authored empty string; the latter is invalid. `openapi.request-reply.maxResponseBytes` inherits its ",
           "package authority ceiling. Telegram `maxMediaBytes` applies only to send; `maxButtons` applies only ",
           "to send and edit. These rules are behavior-level contracts and are therefore maintained in the linked ",
           "bundle references rather than inferred from the descriptor snapshot.", "",
           "## Node index", "",
           "Each property table may scroll horizontally on a narrow viewport. Jump directly to a node:", ""]
    links = [f"[`{behavior}`](#{anchor(behavior)})" for behavior in grouped]
    for offset in range(0, len(links), 7):
        out.append("- " + " · ".join(links[offset:offset + 7]))
    out.append("")
    for behavior, rows in grouped.items():
        descriptor = rows[0]
        outcomes = rows[0]["descriptorOutcomes"]
        if not outcomes or outcomes == "—":
            outcomes = "Not declared"
        out.extend([f"## `{behavior}` {{#{anchor(behavior)}}}", "",
                    f"Canonical runtime rules: {reference(behavior)}. ",
                    f"[Complete GraphML example](../examples/nodes/{behavior}.graphml).", "",
                    "| Catalog field | Runtime descriptor value |",
                    "|---|---|",
                    f"| Display name | {display(descriptor['displayName'])} |",
                    f"| Category | {display(descriptor['category'])} |",
                    f"| Description | {display(descriptor['description'])} |",
                    f"| Visual type | {display(descriptor['visualType'])} |",
                    f"| Agentic | {descriptor['agentic']} |",
                    f"| Capabilities | {display(descriptor['capabilities'])} |",
                    f"| Declared default nature | {display(descriptor['defaultNature'])} |",
                    f"| Declared allowed natures | {display(descriptor['allowedNatures'])} |",
                    f"| Application command allowlist | {display(descriptor['commands'])} |",
                    f"| Runtime concurrency | default {descriptor['runtimeConcurrencyDefault']}; ceiling {descriptor['runtimeConcurrencyCeiling']} |",
                    f"| Outcomes | {display(outcomes)} |", "",
                    "| Property | Display label | Editor help | Type | Required | Default | Allowed values | Adapter | Visible when | Required when | Descriptor limits |",
                    "|---|---|---|---|---:|---|---|---:|---|---|---|"])
        for row in rows:
            if row["property"] == "—":
                out.append("| _No configurable properties_ | — | — | — | — | — | — | — | — | — | — |")
                continue
            out.append("| `{property}` | {label} | {help_text} | `{type}` | {required} | {default} | {allowed} | {adapter} | {visible} | {required_when} | {limits} |".format(
                property=row["property"], label=display(row["propertyDisplayName"]),
                help_text=display(row["propertyDescription"]), type=row["type"], required=row["required"],
                default=display(row["default"]), allowed=display(row["allowed"]),
                adapter=row["adapterBinding"], visible=display(row["visibleWhen"]),
                required_when=display(row["requiredWhen"]), limits=constraint(row)))
        out.append("")
    return "\n".join(line.rstrip() for line in out).rstrip() + "\n"


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    content = render()
    if args.check:
        if not OUTPUT.exists() or OUTPUT.read_text(encoding="utf-8") != content:
            print(f"{OUTPUT.relative_to(ROOT)} is stale; run {Path(__file__).name}")
            return 1
        return 0
    OUTPUT.write_text(content, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
